export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
export const MULTIPLY_COUNTER = "MULTIPLY_COUNTER";

export const LOAD_PRODUCTS_REQUESTED = "LOAD_PRODUCTS_REQUESTED";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_FAILED = "LOAD_PRODUCTS_FAILED";